spring:
  application:
    name: backend


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL81Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/store_db
    username: user
    password: pass
