spring:
  application:
    name: backend

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
#    show-sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    mail:
      host: smtp.gmail.com
      port: 587
      username: username
      password: pass
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

token:
  signing:
    key: 23YG9236BRTB3982H3C289GFH49264G237498GCNF4YT5C7HF0348H9HT235T2
