spring:
  application:
    name: backend


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://localhost:5433/store_db
    username: user
    password: pass
