spring:
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/store_db
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.yandex.ru
    port: 465
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail:
        transport:
          protocol: smtps
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
            trust: smtp.yandex.ru
        sender:
          email: no-reply@example.com
          text: no-reply
        debug: true

sql:
  init:
    data-locations: classpath:init-schema.sql


token:
  signing:
    key: 23YG9236BRTB3982H3C289GFH49264G237498GCNF4YT5C7HF0348H9HT235T2

logging:
  level:
    # org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG