spring:
  application:
    name: backend


  jpa:
    hibernate:
      ddl-auto: update
      use_sql_comments: true
      format_sql: true

  datasource:
    url: jdbc:h2:mem:storedb
    username: admin
    password:
