spring:
  application:
    name: backend

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
#    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5433/store_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

token:
  signing:
    key: 23YG9236BRTB3982H3C289GFH49264G237498GCNF4YT5C7HF0348H9HT235T2
