spring:
  application:
    name: backend

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans=true:

  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:postgresql://127.0.0.1:5433/store_db
    username: user
    password: pass

    driver-class-name: org.postgresql.Driver

    mail:
      host: smtp.gmail.com
      port: 587
      username: mishafromnic@tutamail.com
      password: "bjx3QR2gYDXuAyH"
      test-connection: true
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
          ssl:
            trust: smtp.gmail.com
          sender:
            email: no-reply@example.com
            text: no-reply

token:
  signing:
    key: 23YG9236BRTB3982H3C289GFH49264G237498GCNF4YT5C7HF0348H9HT235T2

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG