spring:
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/store_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.yandex.ru
    port: 465
    username: michealsytch@yandex.ru
    password: xnveichxovfehfyq
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail:
        sender:
          email: no-reply@example.com
          text: no-reply
        debug: true

sql:
  init:
    data-locations: classpath:init-schema.sql


token:
  signing:
    key: 23YG9236BRTB3982H3C289GFH49264G237498GCNF4YT5C7HF0348H9HT235T2

logging:
  level:
    # org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG