spring:
  application:
    name: backend

  jpa:
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      enable_lazy_load_no_trans: true
      allow_update_outside_transaction: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/store_db
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtp
    username: michealsytch@yandex.ru
    password: "xnveichxovfehfyq"
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        ssl:
          trust: smtp.yandex.ru
        sender:
          email: no-reply@example.com
          text: no-reply

mail:
  debug: true

token:
  signing:
    key: 23YG9236BRTB3982H3C289GFH49264G237498GCNF4YT5C7HF0348H9HT235T2

#logging:
#  level:
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG