CREATE TABLE categories
(
    category_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name     VARCHAR(255)                            NOT NULL,
    super_category_id BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (category_id)
);

CREATE TABLE category_product
(
    category_id BIGINT NOT NULL,
    product_id  BIGINT NOT NULL,
    CONSTRAINT pk_category_product PRIMARY KEY (category_id, product_id)
);

CREATE TABLE images
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_product_id BIGINT,
    image_title        VARCHAR(255)                            NOT NULL,
    image_reference    VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE order_products
(
    order_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL
);

CREATE TABLE orders
(
    order_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_user_id BIGINT,
    order_date   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id)
);

CREATE TABLE prices
(
    price_id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_product_id BIGINT,
    price_value        DECIMAL                                 NOT NULL,
    price_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_prices PRIMARY KEY (price_id)
);

CREATE TABLE products
(
    product_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name        VARCHAR(255)                            NOT NULL,
    product_description VARCHAR(255)                            NOT NULL,
    product_sku         VARCHAR(255)                            NOT NULL,
    product_quantity    BIGINT                                  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

CREATE TABLE users
(
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_first_name VARCHAR(255)                            NOT NULL,
    user_last_name  VARCHAR(255)                            NOT NULL,
    user_password   VARCHAR(255)                            NOT NULL,
    user_email      VARCHAR(255)                            NOT NULL,
    role            SMALLINT,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

ALTER TABLE categories
    ADD CONSTRAINT FK_CATEGORIES_ON_SUPER_CATEGORY FOREIGN KEY (super_category_id) REFERENCES categories (category_id);

ALTER TABLE images
    ADD CONSTRAINT FK_IMAGES_ON_PRODUCT_PRODUCT FOREIGN KEY (product_product_id) REFERENCES products (product_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_USER_USER FOREIGN KEY (user_user_id) REFERENCES users (user_id);

ALTER TABLE prices
    ADD CONSTRAINT FK_PRICES_ON_PRODUCT_PRODUCT FOREIGN KEY (product_product_id) REFERENCES products (product_id);

ALTER TABLE category_product
    ADD CONSTRAINT fk_catpro_on_category FOREIGN KEY (category_id) REFERENCES categories (category_id);

ALTER TABLE category_product
    ADD CONSTRAINT fk_catpro_on_product FOREIGN KEY (product_id) REFERENCES products (product_id);

ALTER TABLE order_products
    ADD CONSTRAINT fk_ordpro_on_order FOREIGN KEY (order_id) REFERENCES orders (order_id);

ALTER TABLE order_products
    ADD CONSTRAINT fk_ordpro_on_product FOREIGN KEY (product_id) REFERENCES products (product_id);