-- Удаление всех таблиц, если они существуют, для предотвращения ошибок
DROP TABLE IF EXISTS order_products CASCADE;
DROP TABLE IF EXISTS prices CASCADE;
DROP TABLE IF EXISTS category_product CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Создание таблицы categories
CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    category_name VARCHAR(255) NOT NULL,
    super_category_id BIGINT,
    CONSTRAINT pk_categories PRIMARY KEY (category_id),
    CONSTRAINT FK_CATEGORIES_ON_SUPER_CATEGORY FOREIGN KEY (super_category_id) REFERENCES categories (category_id) ON DELETE SET NULL
);

-- Создание таблицы users
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_first_name VARCHAR(255) NOT NULL,
    user_last_name VARCHAR(255) NOT NULL,
    user_password VARCHAR(255) NOT NULL,
    user_email VARCHAR(255) NOT NULL,
    role SMALLINT,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

-- Создание таблицы products
CREATE TABLE products (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    product_description VARCHAR(255) NOT NULL,
    product_sku VARCHAR(255) NOT NULL,
    product_quantity BIGINT NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (product_id)
);

-- Создание таблицы images
CREATE TABLE images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_product_id BIGINT,
    image_title VARCHAR(255) NOT NULL,
    image_reference VARCHAR(255) NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id),
    CONSTRAINT FK_IMAGES_ON_PRODUCT_PRODUCT FOREIGN KEY (product_product_id) REFERENCES products (product_id) ON DELETE SET NULL
);

-- Создание таблицы orders
CREATE TABLE orders (
    order_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_user_id BIGINT,
    order_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT FK_ORDERS_ON_USER_USER FOREIGN KEY (user_user_id) REFERENCES users (user_id) ON DELETE SET NULL
);

-- Создание таблицы prices
CREATE TABLE prices (
    price_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    product_product_id BIGINT,
    price_value DECIMAL NOT NULL,
    price_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_prices PRIMARY KEY (price_id),
    CONSTRAINT FK_PRICES_ON_PRODUCT_PRODUCT FOREIGN KEY (product_product_id) REFERENCES products (product_id) ON DELETE CASCADE
);

-- Создание таблицы category_product
CREATE TABLE category_product (
    category_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT pk_category_product PRIMARY KEY (category_id, product_id),
    CONSTRAINT fk_catpro_on_category FOREIGN KEY (category_id) REFERENCES categories (category_id) ON DELETE CASCADE,
    CONSTRAINT fk_catpro_on_product FOREIGN KEY (product_id) REFERENCES products (product_id) ON DELETE CASCADE
);

-- Создание таблицы order_products
CREATE TABLE order_products (
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    CONSTRAINT fk_ordpro_on_order FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_ordpro_on_product FOREIGN KEY (product_id) REFERENCES products (product_id) ON DELETE CASCADE
);