version:  '3.1'

volumes:
  pg_store:

services:
  store_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=store_db
    volumes:
      - pg_store:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
